### ISSUE TITLE
Need to figure out how to join the filtered tables 

### ISSUE THREAD

**Issue by eraphael7** [eraphael7/sds192-mp2#1]

**Comment by eraphael7** [comment]
which join should we be using bc inner_join isn't working

**Comment by MaddieHaines** [comment]
Looked at R resources online, found way to join the tables the way I wanted to. See comments to know what each block of code does.

**Comment by eraphael7** [comment]
Did it with left_join, the only reason it wasn't working out was because our rename didn't go through, so once we realised that wasn't working and fixed it left-join worked.
