### ISSUE TITLE
Anticipated problem: We are graphing donations by date, but there are more than one donation by more than one company each day so these need to be additive

### ISSUE THREAD

**Issue by eraphael7** [eraphael7/sds192-mp2#4]

**Comment by MaddieHaines** [comment]
If line graphs don't end up working well for communicating what we want to communicate, a bar chart might work better. Once we get everything in order to make a graph, perhaps we should test both out and see which one works better.

**Comment by kimbrlyzhang** [comment]
used mutate(total = sum(transanction_amt) to solve
